/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.time;

import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADN Telecom
 */
public class ViewTeachers extends javax.swing.JFrame {

    DefaultTableModel model; //DefaultTableModel modl;

    public ViewTeachers() {
        this.setTitle("View Teachers");
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\ADN Telecom\\Desktop\\logo\\coaching.png"));
        initComponents();
        model = (DefaultTableModel) tblteach.getModel();
        //modl = (DefaultTableModel) tl.getModel();
        String s = "C:\\Users\\ADN Telecom\\Desktop\\Student TIme\\TeachersInfo.txt";
        File f = new File(s);
        try {
            BufferedReader b = new BufferedReader(new FileReader(f));
            Object[] tablesLines = b.lines().toArray();
            for (int i = 0; i < tablesLines.length; i++) {
                String ln = tablesLines[i].toString().trim();
                String[] data = ln.split("@@@@");
                String[] modi = new String[6];
                for (int j = 0; j < 6; j++) {
                    modi[j] = data[j];
                }
                if(ln.trim().isEmpty()==false)
                model.addRow(modi);
            }
        } catch (IOException ex) {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        ecnt = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        sub = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        show = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblteach = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel2.setText("Email");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        ecnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ecntActionPerformed(evt);
            }
        });

        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setText("Appointment.t");

        jLabel6.setText("ID");

        jLabel1.setText("Name");

        jLabel3.setText("Subject");

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        tblteach.setAutoCreateRowSorter(true);
        tblteach.setBackground(new java.awt.Color(255, 237, 238));
        tblteach.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tblteach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email", "Subject", "Contact", "Appointment.t"
            }
        ));
        tblteach.getTableHeader().setReorderingAllowed(false);
        tblteach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblteachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblteach);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Teacher's Information");

        jLabel4.setText("Contact");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(show)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ecnt, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jButton4)
                                .addGap(22, 22, 22)
                                .addComponent(jButton5))
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ecnt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int p = -1; // ID or row select korbe
        if (id.getText().trim().isEmpty()) { // row selected na then            
            JOptionPane.showMessageDialog(ViewTeachers.this, "Enter ID");
            return;
        } else {
            String s = id.getText().trim();
            // int p = -1 ;
            for (int i = 0; i < tblteach.getRowCount(); i++) {
                String x = ((String) model.getValueAt(i, 0));
                if (x.equalsIgnoreCase(s)) {
                    p = i;
                    break;
                }
            }
            if (p == -1) {
                JOptionPane.showMessageDialog(ViewTeachers.this, "Invalid ID");
                return;
            }

        }
        Res n = new Res(((String) model.getValueAt(p, 0)), ((String) model.getValueAt(p, 1)), ((String) model.getValueAt(p, 2)), ((String) model.getValueAt(p, 3)), ((String) model.getValueAt(p, 4)), ((String) model.getValueAt(p, 5)));
        // model.removeRow(tblstd.getSelectedRow());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
        homepage m = new homepage();
        m.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void ecntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ecntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ecntActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        tblteach.clearSelection();
    }//GEN-LAST:event_formMouseClicked

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        int p = -1; // ID or row select korbe
        if (tblteach.getSelectedRow() == -1 && id.getText().trim().isEmpty()) { // row selected na then            
            JOptionPane.showMessageDialog(ViewTeachers.this, "Invalid Row and empty ID");
            return;
        } else if (tblteach.getSelectedRow() == -1 && id.getText().trim().isEmpty() != true) {
            String s = id.getText().trim();
            // int p = -1 ;
            for (int i = 0; i < tblteach.getRowCount(); i++) {
                String x = ((String) model.getValueAt(i, 0));
                if (x.equalsIgnoreCase(s)) {
                    p = i;
                    break;
                }
            }
            if (p == -1) {
                JOptionPane.showMessageDialog(ViewTeachers.this, "Invalid ID");
                return;
            }

        } else {
            p = tblteach.getSelectedRow();
        }

        Res n = new Res(((String) model.getValueAt(p, 0)), ((String) model.getValueAt(p, 1)), ((String) model.getValueAt(p, 2)), ((String) model.getValueAt(p, 3)), ((String) model.getValueAt(p, 4)), ((String) model.getValueAt(p, 5)));
        // model.removeRow(tblstd.getSelectedRow());

    }//GEN-LAST:event_showActionPerformed

    private void tblteachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblteachMouseClicked

    }//GEN-LAST:event_tblteachMouseClicked
    class Res {

        public Res() {
            name.setText("");
            email.setText("");
            id.setText("");
            ecnt.setText("");
            time.setText("");
            sub.setText("");
        }

        public Res(String s1, String s2, String s3, String s4, String s5, String s6) {
            name.setText(s2);
            email.setText(s3);
            id.setText(s1);
            ecnt.setText(s5);
            time.setText(s6);
            sub.setText(s4);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Res n = new Res();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int p = -1; // ID or row select korbe
        if (tblteach.getSelectedRow() == -1 && id.getText().trim().isEmpty()) { // row selected na then            
            JOptionPane.showMessageDialog(ViewTeachers.this, "Invalid Row and empty ID");
            return;
        } else if (tblteach.getSelectedRow() == -1 && id.getText().trim().isEmpty() != true) {
            String s = id.getText().trim();
            // int p = -1 ;
            for (int i = 0; i < tblteach.getRowCount(); i++) {
                String x = ((String) model.getValueAt(i, 0));
                x = x.trim();
                if (x.equalsIgnoreCase(s)) {
                    p = i;
                    break;
                }
            }
            if (p == -1) {
                JOptionPane.showMessageDialog(ViewTeachers.this, "Invalid ID");
                return;
            }
        } else {
            p = tblteach.getSelectedRow();
        }
        String s = (String) model.getValueAt(p, 0); // ID number nilam
        //deleting info       
        String s2 = "C:\\Users\\ADN Telecom\\Desktop\\Student TIme\\TeachersInfo.txt"; // file open korlam the studentinfo file
        File f = new File(s2);
        Scanner gt = null;
        try {
            gt = new Scanner(f); // will scan the studentinfo file
        } catch (FileNotFoundException ex) {
        }
        File f2 = new File("C:\\Users\\ADN Telecom\\Desktop\\Student TIme\\y.txt"); // x name a new file banabo jodi na thake thn
        // new file 
        try {
            if (f2.createNewFile()) {
            } else {
            }
        } catch (IOException e) {
        }
        try { // opening a file and want to write in it
            FileWriter x = new FileWriter(f2, false);// x file a likhbo x = f2 , std = f 
            while (gt.hasNext()) {
                String u = gt.nextLine().trim();
                if (u.isEmpty() == false) {
                    String[] str = u.split("@@@@");
                    String a = "";
                    for (int i = 0; i < str.length; i++) {
                        if (i == 0) {
                            a += (str[i]);
                        } else {
                            a += ("@@@@" + str[i]);
                        }
                    }
                    a += "\n";
                    if (str[0].equals(s) == false) {
                        x.write(a);
                    }
                }
            }
            //File f3 = new File("D:\\javaproject\\School Management\\p.txt");
            // f1.renameTo(f);
            x.close();
            //f.renameTo(f3);
        } catch (Exception e) {
            // System.out.println("h k i");
        }
        gt.close();
        File a = new File("C:\\Users\\ADN Telecom\\Desktop\\Student TIme\\y.txt");
        File b = new File("C:\\Users\\ADN Telecom\\Desktop\\Student TIme\\TeachersInfo.txt");
        Scanner get2 = null;
        try {
            // copy everything from x to student
            get2 = new Scanner(a); // scanning x txt file
        } catch (FileNotFoundException ex) {
            //Logger.getLogger(ViewStudents.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            FileWriter h = new FileWriter(b); // ai file a new kore likhbo  
            while (get2.hasNext()) {
                String u = get2.nextLine().trim();
                if (u.isEmpty() == false) {
                    h.write(u);
                    h.write("\n");
                }
            }
            h.close();
        } catch (Exception e) {
        }
        get2.close();
        model.removeRow(tblteach.getSelectedRow());
        Res n = new Res();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTeachers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ecnt;
    private javax.swing.JTextField email;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JButton show;
    private javax.swing.JTextField sub;
    private javax.swing.JTable tblteach;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
